# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Gogo
tagline:          XoomBLog
url:              http://gogoxoom.github.io
paginate:         1
baseurl:          /
author:
  name:           Jesse Wolfe
  url:            https://jessewolfe.com
  email:          jessewolfe@gmail.com

# Custom vars
version:          0.0.1
github:
  repo:           https://gogoxoom.github.io
